### ISSUE TITLE
meta

### ISSUE THREAD

**Issue by benmosher** [benmosher/babel-preset-es2015-argon#1]
- [ ] add README.md
- [ ] mention it totally works for latest Chrome (dev build, anyone?)
- [ ] add repo link to package.json
